version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - python -m pip install selenium
      - python -m pip install html-testRunner
      - wget -N https://chromedriver.storage.googleapis.com/94.0.4606.61/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
  build:
    commands:
      - python test_todo_list_selenium.py
artifacts:
  files:
    - "**/*"
  discard-paths: yes
