version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - apt-get update
      - apt-get install -y chromium-browser
      - wget https://chromedriver.storage.googleapis.com/94.0.4606.61/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - mv chromedriver /usr/local/bin/
      - chmod +x /usr/local/bin/chromedriver
      - python -m pip install selenium
      - python -m pip install html-testRunner
  build:
    commands:
      - python test_todo_list_selenium.py

artifacts:
  files:
    - "**/*"
  base-directory: "./reports"
