version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - python -m pip install selenium
      - python -m pip install html-testRunner
      - wget -N https://chromedriver.storage.googleapis.com/94.0.4606.61/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - pip install awscli
  pre_build:
    commands:
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set default.region $AWS_REGION
  build:
    commands:
      - python test_todo_list_selenium.py
  post_build:
    commands:
      - aws s3 cp reports/TestResults___main__.ToDoListTests.html s3://automated-test-reports/reports/
      - echo "HTML report uploaded to S3"

artifacts:
  files:
    - "**/*"
  discard-paths: yes
